@echo off
cd build
REM cmake -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE  -DCMAKE_INSTALL_PREFIX="../../.." -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=Debug .. -G"Visual Studio 16 2019" -Ax64
REM 构建64位 静态库
cmake .. -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX="./install" -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=Debug -G "Visual Studio 16 2019" -A x64
